/**
 * Creator/demo feed posts (batch A) for the mock timeline.
 *
 * Exports: CREATOR_FEED_POSTS_A
 * Depends on: seed profiles MOCK_ME_ID, post-media, helpers
 */

import { DEMO_STATUS_PHOTOS } from "@/lib/post-media";
import { MOCK_ME_ID } from "../profiles";
import type { MockPost } from "../types";
import { canvas, DEMO_TRANSITION_GRADIENTS } from "./helpers";

export const CREATOR_FEED_POSTS_A: MockPost[] = [
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
    author_id: MOCK_ME_ID,
    post_type: "text",
    canvas_html: canvas({
      text: "Start with the smallest clear promise. Let the first frame breathe. Give every sentence one job. Make the rhythm easy to follow. Leave the final page glowing.",
      font: "Space Grotesk",
      size: 82,
      color: "#ffffff",
      entrance: "scale",
      loop: "pulse",
      backgroundStyle: "transition",
      gradientPath: DEMO_TRANSITION_GRADIENTS,
    }),
    media_urls: [],
    bg_gradient: DEMO_TRANSITION_GRADIENTS[0] ?? "linear-gradient(135deg,#FF006E,#8338EC)",
    created_at: "2026-06-16T07:20:00.000Z",
  },
  {
    id: "19191919-0619-4619-8619-191919191919",
    author_id: "44444444-4444-4444-8444-444444444444",
    post_type: "image",
    canvas_html: canvas({
      text: [
        "Ao thu lạnh lẽo nước trong veo,",
        "Một chiếc thuyền câu bé tẻo teo.",
        "Sóng biếc theo làn hơi gợn tí,",
        "Lá vàng trước gió khẽ đưa vèo.",
        "Tầng mây lơ lửng trời xanh ngắt,",
        "Ngõ trúc quanh co khách vắng teo.",
        "Tựa gối buông cần lâu chẳng được,",
        "Cá đâu đớp động dưới chân bèo.",
      ].join("\n"),
      font: "Playfair Display",
      size: 72,
      color: "#FFF7ED",
      weight: 700,
      letterSpacing: -0.015,
      entrance: "blur",
      loop: "float",
      tempo: "slow",
      rhythm: "poetic",
      y: 54,
    }),
    media_urls: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=900&q=80",
    ],
    bg_gradient: "linear-gradient(135deg,#F8C8DC,#7C3AED)",
    created_at: "2026-06-16T07:19:30.000Z",
  },
  {
    id: "dadadada-dada-4ada-8ada-dadadadada05",
    author_id: MOCK_ME_ID,
    post_type: "image",
    canvas_html: canvas({
      text: "Tiếng Việt cần khoảng thở dài hơn một chút. Mỗi trang nên giữ trọn một ý rõ. Dấu sắc dấu huyền cũng tạo nhịp riêng. Khi chữ hiện chậm, cảm xúc dễ bám hơn. Người đọc có thể nhớ câu cuối lâu hơn. Đây là bài thử cho nhịp hấp thụ.",
      font: "Inter",
      size: 70,
      color: "#ffffff",
      entrance: "fade",
      loop: "float",
      tempo: "slow",
    }),
    media_urls: [DEMO_STATUS_PHOTOS.vietnameseRhythm],
    bg_gradient: "linear-gradient(135deg,#00B4D8,#FF006E)",
    created_at: "2026-06-16T07:19:00.000Z",
  },
  {
    id: "bebebebe-bebe-4ebe-8ebe-bebebebebe06",
    author_id: "33333333-3333-4333-8333-333333333333",
    post_type: "image",
    canvas_html: canvas({
      text: "Nếu thông tin dày, mở bằng hình ảnh quen. Sau đó đặt luận điểm ở giữa màn hình. Đừng ép người xem hiểu quá nhanh. Cho họ một nhịp để tự đồng ý. Khi trang đổi, ý mới mới bắt đầu. Nội dung tốt cần thở cùng người đọc.",
      font: "Inter",
      size: 70,
      color: "#ffffff",
      entrance: "blur",
      loop: "pulse",
      tempo: "steady",
    }),
    media_urls: [DEMO_STATUS_PHOTOS.denseInfo],
    bg_gradient: "linear-gradient(135deg,#FFBE0B,#06FFA5)",
    created_at: "2026-06-16T07:18:00.000Z",
  },
  {
    id: "fafafafa-fafa-4afa-8afa-fafafafafa07",
    author_id: "44444444-4444-4444-8444-444444444444",
    post_type: "image",
    canvas_html: canvas({
      text: "Buổi sáng ở Hà Nội có màu rất mềm. Một câu ngắn có thể giữ lại hơi sương. Tôi muốn chữ đi qua như tiếng xe xa. Không cần quá nhanh, chỉ cần đủ gần. Đọc xong vẫn còn một chút lặng. Hãy để mắt tự chọn nơi dừng.",
      font: "Inter",
      size: 68,
      color: "#ffffff",
      entrance: "slide",
      loop: "float",
      tempo: "steady",
      rotation: -1,
    }),
    media_urls: [DEMO_STATUS_PHOTOS.hanoiMorning],
    bg_gradient: "linear-gradient(135deg,#3A86FF,#7209B7)",
    created_at: "2026-06-16T07:16:00.000Z",
  },
  {
    id: "91919191-9191-4919-8919-919191919108",
    author_id: "66666666-6666-4666-8666-666666666666",
    post_type: "image",
    canvas_html: canvas({
      text: "Trong một cuộc trò chuyện, tốc độ không phải tất cả. Có lúc câu trả lời hay nhất là im lặng. Chữ chuyển động nên giống hơi thở. Vào đúng lúc, ra đúng lúc. Người xem sẽ tự theo nếu nhịp thật.",
      font: "Inter",
      size: 72,
      color: "#ffffff",
      entrance: "scale",
      loop: "none",
      tempo: "snappy",
    }),
    media_urls: [DEMO_STATUS_PHOTOS.conversation],
    bg_gradient: "linear-gradient(135deg,#F72585,#118AB2)",
    created_at: "2026-06-16T07:14:00.000Z",
  },
  {
    id: "abababab-abab-4aba-8aba-ababababab01",
    author_id: "22222222-2222-4222-8222-222222222222",
    post_type: "image",
    canvas_html: canvas({
      text: "Một ý tưởng nhỏ cũng cần nhịp. Hãy để câu đầu thở. Rồi ánh sáng tự tìm người.",
      font: "Inter",
      size: 78,
      color: "#ffffff",
      entrance: "fade",
      loop: "float",
      tempo: "steady",
    }),
    media_urls: [DEMO_STATUS_PHOTOS.smallIdea],
    bg_gradient: "linear-gradient(135deg,#118AB2,#06D6A0)",
    created_at: "2026-06-16T07:17:00.000Z",
  },
  {
    id: "cdcdcdcd-cdcd-4dcd-8dcd-cdcdcdcdcd02",
    author_id: "33333333-3333-4333-8333-333333333333",
    post_type: "text",
    canvas_html: canvas({
      text: "Đừng vội làm mọi thứ rực rỡ. Một khoảng lặng đủ giữ mắt. Một chữ đúng cũng biết sáng.",
      font: "Inter",
      size: 74,
      color: "#ffffff",
      entrance: "blur",
      loop: "pulse",
      tempo: "slow",
      backgroundPattern: "chevron",
    }),
    media_urls: [],
    bg_gradient: null,
    created_at: "2026-06-16T07:12:00.000Z",
  },
  {
    id: "efefefef-efef-4efe-8efe-efefefefef03",
    author_id: "44444444-4444-4444-8444-444444444444",
    post_type: "text",
    canvas_html: canvas({
      text: "Sài Gòn chậm lại sau cơn mưa. Màn hình sáng như một quán nhỏ. Ai cũng có câu chuyện riêng.",
      font: "Inter",
      size: 72,
      color: "#ffffff",
      entrance: "slide",
      loop: "float",
      tempo: "steady",
      rotation: -1,
      backgroundPattern: "circuit",
    }),
    media_urls: [],
    bg_gradient: null,
    created_at: "2026-06-16T07:08:00.000Z",
  },
  {
    id: "acacacac-acac-4aca-8aca-acacacacac04",
    author_id: "66666666-6666-4666-8666-666666666666",
    post_type: "image",
    canvas_html: canvas({
      text: "Bữa cơm tối cần nhiều tiếng cười. Tin nhắn dài để dành sau. Trước hết hãy ngồi thật gần.",
      font: "Inter",
      size: 76,
      color: "#ffffff",
      entrance: "scale",
      loop: "none",
      tempo: "snappy",
    }),
    media_urls: [DEMO_STATUS_PHOTOS.dinnerTable],
    bg_gradient: null,
    created_at: "2026-06-16T07:03:00.000Z",
  }
];
