/**
 * Animation template catalog (batch A) for create-studio.
 *
 * Exports: ANIMATION_TEMPLATES_A
 * Depends on: create-studio types, templates/media
 */

import type { AnimationTemplate } from "../../types";

export const ANIMATION_TEMPLATES_A: AnimationTemplate[] = [
  {
    id: "paper-headline",
    label: "paper headline",
    mood: "scene · editorial",
    backdrop: { mode: "scene", sceneId: "paper-cut-sunrise" },
    spec: {
      font: "Bebas Neue",
      size: 112,
      color: "#ffffff",
      weight: 900,
      letterSpacing: -0.02,
      entrance: "slide",
      loop: "pulse",
      tempo: "steady",
      rhythm: "burst",
      x: 50,
      y: 50,
      rotation: -1,
      backgroundScene: "paper-cut-sunrise",
    },
  },
  {
    id: "rose-verse",
    label: "rose verse",
    mood: "slow · poetic",
    backdrop: { mode: "gradient", gradient: "linear-gradient(135deg,#F8C8DC,#7C3AED)" },
    spec: {
      font: "Playfair Display",
      size: 98,
      color: "#FFF7ED",
      weight: 700,
      letterSpacing: -0.015,
      entrance: "blur",
      loop: "float",
      tempo: "slow",
      rhythm: "poetic",
      x: 50,
      y: 52,
      rotation: -1,
    },
  },
  {
    id: "ink-memo",
    label: "ink memo",
    mood: "scene · quiet print",
    backdrop: { mode: "scene", sceneId: "paper-cut-noir" },
    spec: {
      font: "Playfair Display",
      size: 96,
      color: "#FFF7ED",
      weight: 800,
      letterSpacing: -0.015,
      entrance: "blur",
      loop: "float",
      tempo: "slow",
      rhythm: "poetic",
      x: 50,
      y: 54,
      rotation: 0,
      backgroundScene: "paper-cut-noir",
    },
  },
  {
    id: "pattern-current",
    label: "pattern current",
    mood: "continuous · seamless",
    backdrop: { mode: "pattern", patternId: "waves" },
    spec: {
      font: "Space Grotesk",
      size: 100,
      color: "#ffffff",
      weight: 900,
      letterSpacing: -0.035,
      entrance: "slide",
      loop: "float",
      tempo: "steady",
      rhythm: "smooth",
      x: 50,
      y: 52,
      rotation: 0,
      backgroundPattern: "waves",
    },
  },
  {
    id: "aqua-fold",
    label: "aqua fold",
    mood: "scene · cool cut",
    backdrop: { mode: "scene", sceneId: "paper-cut-aqua" },
    spec: {
      font: "Space Grotesk",
      size: 102,
      color: "#ffffff",
      weight: 900,
      letterSpacing: -0.04,
      entrance: "split",
      loop: "float",
      tempo: "steady",
      rhythm: "stagger",
      x: 50,
      y: 51,
      rotation: 1,
      backgroundScene: "paper-cut-aqua",
    },
  },
  {
    id: "neon-burst",
    label: "neon burst",
    mood: "snappy · burst",
    backdrop: { mode: "gradient", gradient: "linear-gradient(135deg,#FF006E,#8338EC)" },
    spec: {
      font: "Bebas Neue",
      size: 114,
      color: "#ffffff",
      weight: 900,
      letterSpacing: -0.02,
      entrance: "scale",
      loop: "pulse",
      tempo: "snappy",
      rhythm: "burst",
      x: 50,
      y: 50,
      rotation: -1,
    },
  }
];
